### ISSUE TITLE
Need mobile to collapse the header + filtering

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#137]
![img_0047](https://user-images.githubusercontent.com/106187/47259397-20b91f80-d477-11e8-9f89-c76700199b6d.png)

The content on most sub pages (like Work seen here) takes two swipes on a giant iphone.
Collapse the main picture AND filtering.
?

**Comment by craigmcginley** [comment]
@sel2sm @jen-p @BrysonWong1 @Parsuree thoughts here? No hero and collapsed filtering on mobile?

**Comment by sel2sm** [comment]
I lean towards consistency, but this is tempting. I'm for this idea.. or at least test/prototype to see how the experience would be. How about the rest of you all?

**Comment by BrysonWong1** [comment]
A collapsed image sounds good to more quickly get into the content. The collapsed menu might be a bit trickier where we balance the tradeoff between visible access of navigation and engagement by getting into the content.
I like the idea of testing to resolve this and above the fold on main pages are generally worth testing.  But rather than assume this is where we should focus our efforts, let's take a look at the analytics and identify and prioritize issues across the site. Ill review them in the next couple days and we can work on a couple a b tests.

**Comment by jsonin** [comment]
Start with collapsing the image (maybe no image?), and putting the filters in a single row, separated by commas.

"Care Management, Health IT, Patient Engagement, Precision Medicine, Public Health, Open Source"

Or suggest something else. 
Just Go!

**Comment by jen-p** [comment]
shorten hero, All > View All work and pre-collapsed on mobile

**Comment by craigmcginley** [comment]
"Add a filter"

**Comment by craigmcginley** [comment]
Done in b8bf3ec66d7d178b75ecd3d6595aa8489c6d2ddc and 8dafa0cd04b37d3c05aba9d055870c4f81f8cb32
