### ISSUE TITLE
References... didn't even see them

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com#87]
Until I click on the number (duh).
https://www.goinvo.com/work/mt-sinai-consent

But they're utterly lost under the "Up Next" section.
Do the references belong above the up next? Especially for case studies, the refs aren't more than 10.
?

**Comment by sel2sm** [comment]
I don't know about putting them ahead of the up next. Occasionally, there are a lot of references. I think references don't matter on their own. Usually, I care if the website has them as I'm reading and come across something that needs proof. In that use case I want to know that there is a reference. The current design works for that because as you're reading the sentence you look for the number and it's there. 

Just my two cents.

**Comment by craigmcginley** [comment]
Resolved as non-issue
